Server:
  RunMode: debug
  HttpPort: 8088
  ReadTimeout: 60
  WriteTimeout: 60

Mysql:
  UserName: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: test
  TablePrefix: geek_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30